config/routes.rb
Rails.application.routes.draw do
  resources :boolean_inputs, controller: 'inputs/boolean_inputs', as: :inputs_boolean_inputs
  resources :text_inputs, controller: 'inputs/text_inputs', as: :inputs_text_inputs
  resources :inputs
  resources :forms
  resources :pages
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/input.rb
class Input < ApplicationRecord
  belongs_to :inputable, polymorphic: true
  belongs_to :form
end

app/models/inputs.rb
module Inputs
  def self.table_name_prefix
    "inputs_"
  end
end

app/models/inputs/boolean_input.rb
class Inputs::BooleanInput < ApplicationRecord
  include Inputable

  def self.inheritance_column
    nil
  end
end

app/models/inputs/text_input.rb
class Inputs::TextInput < ApplicationRecord
  include Inputable
end

app/controllers/inputs/boolean_inputs_controller.rb
class Inputs::BooleanInputsController < ApplicationController
  before_action :set_inputs_boolean_input, only: %i[ show edit update destroy ]

  # GET /inputs/boolean_inputs or /inputs/boolean_inputs.json
  def index
    @inputs_boolean_inputs = Inputs::BooleanInput.all
  end

  # GET /inputs/boolean_inputs/1 or /inputs/boolean_inputs/1.json
  def show
  end

  # GET /inputs/boolean_inputs/new
  def new
    @inputs_boolean_input = Inputs::BooleanInput.new
  end

  # GET /inputs/boolean_inputs/1/edit
  def edit
  end

  # POST /inputs/boolean_inputs or /inputs/boolean_inputs.json
  def create
    @inputs_boolean_input = Inputs::BooleanInput.new(inputs_boolean_input_params)

    respond_to do |format|
      if @inputs_boolean_input.save
        format.html { redirect_to inputs_boolean_input_url(@inputs_boolean_input), notice: "Boolean input was successfully created." }
        format.json { render :show, status: :created, location: @inputs_boolean_input }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inputs_boolean_input.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inputs/boolean_inputs/1 or /inputs/boolean_inputs/1.json
  def update
    respond_to do |format|
      if @inputs_boolean_input.update(inputs_boolean_input_params)
        format.html { redirect_to inputs_boolean_input_url(@inputs_boolean_input), notice: "Boolean input was successfully updated." }
        format.json { render :show, status: :ok, location: @inputs_boolean_input }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inputs_boolean_input.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inputs/boolean_inputs/1 or /inputs/boolean_inputs/1.json
  def destroy
    @inputs_boolean_input.destroy

    respond_to do |format|
      format.html { redirect_to inputs_boolean_inputs_url, notice: "Boolean input was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inputs_boolean_input
      @inputs_boolean_input = Inputs::BooleanInput.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inputs_boolean_input_params
      params.require(:inputs_boolean_input).permit(:name, :label, :type)
    end
end

app/controllers/inputs/text_inputs_controller.rb
class Inputs::TextInputsController < ApplicationController
  before_action :set_inputs_text_input, only: %i[ show edit update destroy ]

  # GET /inputs/text_inputs or /inputs/text_inputs.json
  def index
    @inputs_text_inputs = Inputs::TextInput.all
  end

  # GET /inputs/text_inputs/1 or /inputs/text_inputs/1.json
  def show
  end

  # GET /inputs/text_inputs/new
  def new
    @inputs_text_input = Inputs::TextInput.new
  end

  # GET /inputs/text_inputs/1/edit
  def edit
  end

  # POST /inputs/text_inputs or /inputs/text_inputs.json
  def create
    @inputs_text_input = Inputs::TextInput.new(inputs_text_input_params)

    respond_to do |format|
      if @inputs_text_input.save
        format.html { redirect_to inputs_text_input_url(@inputs_text_input), notice: "Text input was successfully created." }
        format.json { render :show, status: :created, location: @inputs_text_input }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @inputs_text_input.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inputs/text_inputs/1 or /inputs/text_inputs/1.json
  def update
    respond_to do |format|
      if @inputs_text_input.update(inputs_text_input_params)
        format.html { redirect_to inputs_text_input_url(@inputs_text_input), notice: "Text input was successfully updated." }
        format.json { render :show, status: :ok, location: @inputs_text_input }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @inputs_text_input.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inputs/text_inputs/1 or /inputs/text_inputs/1.json
  def destroy
    @inputs_text_input.destroy

    respond_to do |format|
      format.html { redirect_to inputs_text_inputs_url, notice: "Text input was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inputs_text_input
      @inputs_text_input = Inputs::TextInput.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def inputs_text_input_params
      params.require(:inputs_text_input).permit(:name, :label)
    end
end

app/controllers/inputs_controller.rb
class InputsController < ApplicationController
  before_action :set_input, only: %i[ show edit update destroy ]

  # GET /inputs or /inputs.json
  def index
    @inputs = Input.all
  end

  # GET /inputs/1 or /inputs/1.json
  def show
  end

  # GET /inputs/new
  def new
    @input = Input.new
  end

  # GET /inputs/1/edit
  def edit
  end

  # POST /inputs or /inputs.json
  def create
    @input = Input.new(input_params)

    respond_to do |format|
      if @input.save
        format.html { redirect_to input_url(@input), notice: "Input was successfully created." }
        format.json { render :show, status: :created, location: @input }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @input.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inputs/1 or /inputs/1.json
  def update
    respond_to do |format|
      if @input.update(input_params)
        format.html { redirect_to input_url(@input), notice: "Input was successfully updated." }
        format.json { render :show, status: :ok, location: @input }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @input.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inputs/1 or /inputs/1.json
  def destroy
    @input.destroy

    respond_to do |format|
      format.html { redirect_to inputs_url, notice: "Input was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_input
      @input = Input.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def input_params
      params.require(:input).permit(:inputable_id, :inputable_type, :position, :form_id)
    end
end

app/helpers/inputs/boolean_inputs_helper.rb
module Inputs::BooleanInputsHelper
end

app/helpers/inputs/text_inputs_helper.rb
module Inputs::TextInputsHelper
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/views/inputs/text_inputs/_form.html.erb
<%= form_with(model: inputs_text_input) do |form| %>
  <% if inputs_text_input.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(inputs_text_input.errors.count, "error") %> prohibited this inputs_text_input from being saved:</h2>

      <ul>
        <% inputs_text_input.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :label, style: "display: block" %>
    <%= form.text_field :label %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/inputs/text_inputs/_text_input.html.erb
<div id="<%= dom_id text_input %>">
  <p>
    <strong>Name:</strong>
    <%= text_input.name %>
  </p>

  <p>
    <strong>Label:</strong>
    <%= text_input.label %>
  </p>

</div>

app/views/inputs/text_inputs/edit.html.erb
<h1>Editing text input</h1>

<%= render "form", inputs_text_input: @inputs_text_input %>

<br>

<div>
  <%= link_to "Show this text input", @inputs_text_input %> |
  <%= link_to "Back to text inputs", inputs_text_inputs_path %>
</div>

app/views/inputs/text_inputs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Text inputs</h1>

<div id="inputs_text_inputs">
  <% @inputs_text_inputs.each do |inputs_text_input| %>
    <%= render inputs_text_input %>
    <p>
      <%= link_to "Show this text input", inputs_text_input %>
    </p>
  <% end %>
</div>

<%= link_to "New text input", new_inputs_text_input_path %>

app/views/inputs/text_inputs/new.html.erb
<h1>New text input</h1>

<%= render "form", inputs_text_input: @inputs_text_input %>

<br>

<div>
  <%= link_to "Back to text inputs", inputs_text_inputs_path %>
</div>

app/views/inputs/text_inputs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @inputs_text_input %>

<div>
  <%= link_to "Edit this text input", edit_inputs_text_input_path(@inputs_text_input) %> |
  <%= link_to "Back to text inputs", inputs_text_inputs_path %>

  <%= button_to "Destroy this text input", @inputs_text_input, method: :delete %>
</div>