config/routes.rb
Rails.application.routes.draw do
  resources :boolean_inputs, controller: 'inputs/boolean_inputs', as: :inputs_boolean_inputs
  resources :text_inputs, controller: 'inputs/text_inputs', as: :inputs_text_inputs
  resources :inputs
  resources :forms
  resources :pages
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_form, only: %i[ show edit update destroy ]

  # GET /forms or /forms.json
  def index
    @forms = Form.all
  end

  # GET /forms/1 or /forms/1.json
  def show
  end

  # GET /forms/new
  def new
    @form = Form.new
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms or /forms.json
  def create
    @form = Form.new(form_params)

    respond_to do |format|
      if @form.save
        format.html { redirect_to form_url(@form), notice: "Form was successfully created." }
        format.json { render :show, status: :created, location: @form }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1 or /forms/1.json
  def update
    respond_to do |format|
      if @form.update(form_params)
        format.html { redirect_to form_url(@form), notice: "Form was successfully updated." }
        format.json { render :show, status: :ok, location: @form }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1 or /forms/1.json
  def destroy
    @form.destroy

    respond_to do |format|
      format.html { redirect_to forms_url, notice: "Form was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def form_params
      params.require(:form).permit(:name, :legend, :name, :page_id)
    end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<%= form_with(model: form) do |f| %>
  <% if form.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(form.errors.count, "error") %> prohibited this form from being saved:</h2>

      <ul>
        <% form.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name, style: "display: block" %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :legend, style: "display: block" %>
    <%= f.text_field :legend %>
  </div>

  <div>
    <%= f.label :page_id, style: "display: block" %>
    <%= f.select :page_id, Page.all.limit(500).pluck(:title, :id), include_blank: true %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/forms/_form_partial.html.erb
<div id="<%= dom_id form %>">
  <p>
    <strong>Name:</strong>
    <%= form.name %>
  </p>

  <p>
    <strong>Legend:</strong>
    <%= form.legend %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= form.name %>
  </p>

  <p>
    <strong>Page:</strong>
    <%= form.page_id %>
  </p>

</div>

app/views/forms/edit.html.erb
<h1>Editing form</h1>

<%= render "form", form: @form %>

<br>

<div>
  <%= link_to "Show this form", @form %> |
  <%= link_to "Back to forms", forms_path %>
</div>

app/views/forms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Forms</h1>

<div id="forms">
  <% @forms.each do |form| %>
    <%= render form %>
    <p>
      <%= link_to "Show this form", form %>
    </p>
  <% end %>
</div>

<%= link_to "New form", new_form_path %>

app/views/forms/new.html.erb
<h1>New form</h1>

<%= render "form", form: @form %>

<br>

<div>
  <%= link_to "Back to forms", forms_path %>
</div>

app/views/forms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @form %>

<div>
  <%= link_to "Edit this form", edit_form_path(@form) %> |
  <%= link_to "Back to forms", forms_path %>

  <%= button_to "Destroy this form", @form, method: :delete %>
</div>